---
- name: Stop play execution depending on yum return code
  hosts: all
  tasks:

    - name: Run yum update
      yum:
        name: '*'
        state: latest
        exclude: kernel*,foo*
        # Exclude any packages that cause exceptions to patching
      async: 3600
      # After the time limit of 1hr (in seconds) runs out, the yum process on the remote nodes will be terminated.
      poll: 60
      # Checks the status of the yum run every 60 seconds
      register: yum_result
      # Captures the result of the yum command

    - name: Reboot system if yum succeeds
      reboot:
      when: yum_result.rc == 0 and yum_result.msg != 'Nothing to do'
      # Only reboot if yum command result exits with a "0" code, AND if yum command actually updates packages
